# syntax=docker/dockerfile:1

ARG ORO_BASELINE_VERSION=master-latest
ARG ORO_IMAGE_FROM=docker.io/oroinc/test

FROM ${ORO_IMAGE_FROM}:${ORO_BASELINE_VERSION}

ARG ORO_IMAGE_FROM
ARG ORO_BASELINE_VERSION

ENV ORO_APP_FOLDER=/var/www/oro \
    ORO_USER=root \
    ORO_USER_RUNTIME=www-data

LABEL com.oroinc.orocloud.app="/var/www/oro" \
    com.oroinc.orocloud.image_type="test" \
    org.opencontainers.image.title="Application test image" \
    org.opencontainers.image.description="Application test image. Used for run functional and behat tests" \
    org.opencontainers.image.authors="ORO Inc." \
    org.opencontainers.image.vendor="ORO Inc." \
    org.opencontainers.image.url="https://github.com/laboro/dev/blob/master/docker-build/docker/README.md" \
    org.opencontainers.image.documentation="https://github.com/laboro/dev/blob/master/docker-build/docker/README.md" \
    org.opencontainers.image.base.name="${ORO_IMAGE_FROM}:${ORO_BASELINE_VERSION}"

RUN --mount=type=bind,target=/source \
    groupadd --system --gid 2001 $ORO_USER_RUNTIME && useradd --home-dir $ORO_APP_FOLDER/var --uid 2002 --gid $ORO_USER_RUNTIME --no-create-home --system $ORO_USER_RUNTIME && \
    rsync -a --exclude-from=/source/.rsync-exclude-test --chown="$ORO_USER":"$ORO_USER_RUNTIME" /source/ $ORO_APP_FOLDER && \
    chown -R "$ORO_USER_RUNTIME":"$ORO_USER_RUNTIME" "$ORO_APP_FOLDER"/var/{data,cache,logs,sessions,maintenance} 2>/dev/null; \
    chown -R "$ORO_USER_RUNTIME":"$ORO_USER_RUNTIME" "$ORO_APP_FOLDER"/public/media 2>/dev/null; \
    chown -R "$ORO_USER_RUNTIME":"$ORO_USER" /var/log/php-fpm && \
    chown -R "$ORO_USER":"$ORO_USER_RUNTIME" /var/lib/php/{opcache,session,wsdlcache}

WORKDIR $ORO_APP_FOLDER
VOLUME "$ORO_APP_FOLDER/var/cache"
