x-depends_on: &default-depends_on
  "db":
    condition: service_healthy
  "mail":
    condition: service_started

x-volumes_ce: &default-volumes_ce
  - public_storage:/var/www/oro/public/media
  - private_storage:/var/www/oro/var/data


services:
  web:
    volumes:
      - public_storage:/var/www/oro/public/media:ro
      - private_storage:/var/www/oro/var/data:ro

  web-init:
    command:
      - -c
      - |
        /usr/local/bin/docker-entrypoint.sh nginx-init && sed -i '/gridfs/d; /mongo/d' /opt/oro-nginx/etc/sites-available/*.conf

  php-fpm-app:
    depends_on:
      <<: *default-depends_on
    volumes: *default-volumes_ce

  ws:
    volumes: *default-volumes_ce

  consumer:
    volumes: *default-volumes_ce

  cron:
    volumes: *default-volumes_ce

  operator:
    volumes: *default-volumes_ce

  install:
    depends_on:
      <<: *default-depends_on
    volumes: *default-volumes_ce

  install-test:
    depends_on:
      <<: *default-depends_on
    volumes: *default-volumes_ce

  functional:
    depends_on:
      <<: *default-depends_on
    volumes: *default-volumes_ce

  behat-init:
    depends_on:
      <<: *default-depends_on

  behat:
    depends_on:
      <<: *default-depends_on
    volumes: *default-volumes_ce

  restore:
    depends_on:
      <<: *default-depends_on
    volumes: *default-volumes_ce

  restore-test:
    depends_on:
      <<: *default-depends_on
    volumes: *default-volumes_ce

  update:
    depends_on:
      <<: *default-depends_on
    volumes: *default-volumes_ce

  update-test:
    depends_on:
      <<: *default-depends_on
    volumes: *default-volumes_ce

  warmup-cache:
    depends_on:
      <<: *default-depends_on
    volumes: *default-volumes_ce

  backup:
    build:
      target: backup-files
  
  backup-test:
    build:
      target: backup-files
  

volumes:
  public_storage: {}
  private_storage: {}
