# Used if set variable ORO_DEBUGGER=-xdebug

x-depends_on: &default-depends_on
  "db":
    condition: service_healthy
  "search-engine":
    condition: service_healthy
  "mq":
    condition: service_healthy
  "session-storage":
    condition: service_healthy
  "file-storage":
    condition: service_healthy
  "mail":
    condition: service_started

services:
  volume-init:
    image: $ORO_IMAGE_INIT${ORO_LANGUAGE_SUFFIX-}:$ORO_IMAGE_TAG
    user: root
    command:
      - -c
      - |
        find /etc -type f -ipath '*/php.d/*' -name '*xdebug.ini' -print0 2>/dev/null | xargs -0 -r sed -i '/zend_extension=xdebug/s/.*/zend_extension=xdebug.so/g'
    volumes:
      - etc-opt-remi:/etc/opt/remi

  restore:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - etc-opt-remi:/etc/opt/remi

  restore-test:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      <<: *default-depends_on
      "volume-init":
        condition: service_completed_successfully
    volumes:
      - etc-opt-remi:/etc/opt/remi

  install:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      <<: *default-depends_on
      "volume-init":
        condition: service_completed_successfully
    volumes:
      - etc-opt-remi:/etc/opt/remi

  install-test:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      <<: *default-depends_on
      "volume-init":
        condition: service_completed_successfully
    volumes:
      - etc-opt-remi:/etc/opt/remi

  update:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      <<: *default-depends_on
      "volume-init":
        condition: service_completed_successfully
    volumes:
      - etc-opt-remi:/etc/opt/remi

  update-test:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      <<: *default-depends_on
      "volume-init":
        condition: service_completed_successfully
    volumes:
      - etc-opt-remi:/etc/opt/remi

  operator:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - etc-opt-remi:/etc/opt/remi

  php-fpm-app:
    image: $ORO_IMAGE_BASE_RUNTIME_DEBUG:$ORO_BASELINE_VERSION
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - etc-opt-remi:/etc/opt/remi

  consumer:
    image: $ORO_IMAGE_BASE_RUNTIME_DEBUG:$ORO_BASELINE_VERSION
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - etc-opt-remi:/etc/opt/remi

  ws:
    image: $ORO_IMAGE_BASE_RUNTIME_DEBUG:$ORO_BASELINE_VERSION
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - etc-opt-remi:/etc/opt/remi

  cron:
    image: $ORO_IMAGE_BASE_RUNTIME_DEBUG:$ORO_BASELINE_VERSION
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - etc-opt-remi:/etc/opt/remi

  behat:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - etc-opt-remi:/etc/opt/remi

  functional:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - etc-opt-remi:/etc/opt/remi

volumes:
  etc-opt-remi: {}