services:
  session-storage:
    image: ${ORO_PROJECT}redis:${ORO_REDIS_VER}
    command: redis-server --bind 0.0.0.0
    labels:
      com.symfony.server.service-prefix: ORO_REDIS
    healthcheck:
      test: "[ $$(redis-cli ping) = 'PONG' ]"
      interval: 15s
      timeout: 30s
      start_period: 20s
    restart: unless-stopped
