services:
  proxy:
    environment:
      CAROOT: ${CAROOT-$ORO_CAROOT}
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    volumes:
      - ssl-certs:/etc/nginx/certs
      - etc-pki:/etc/pki

  proxy-behat:
    environment:
      CAROOT: $ORO_CAROOT
    volumes:
      - ssl-certs:/etc/nginx/certs
      - etc-pki:/etc/pki
  
  behat:
    environment:
      CAROOT: $ORO_CAROOT
    volumes:
      - etc-pki:/etc/pki

  restore:
    environment:
      CAROOT:
      ORO_CAROOT:
    volumes:
      - cache:/var/www/oro/var/cache
      - ${CAROOT-/var/empty}:${CAROOT-/var/empty}
      - etc-pki:/etc/pki
      - ./../docker/docker-entrypoint-init.sh:/usr/local/bin/docker-entrypoint.sh

  chrome:
    environment:
      CAROOT: $ORO_CAROOT
    volumes:
      - ssl-certs:/etc/nginx/certs
      - etc-pki:/etc/pki

volumes:
  ssl-certs: {}
  etc-pki: {}