services:
  waf:
    ports:
      - published: 80
        target: $ORO_NGINX_HTTP_PORT
      - published: 443
        target: $ORO_NGINX_HTTPS_PORT

  waf-behat:
    cap_add:
      - NET_BIND_SERVICE
    expose:
      - $ORO_NGINX_HTTP_PORT
      - $ORO_NGINX_HTTPS_PORT
    healthcheck:
      test: "curl -ILf ${ORO_APP_PROTOCOL}://${ORO_APP_DOMAIN}:${ORO_NGINX_HTTPS_PORT}/"
      interval: 15s
      timeout: 30s
      start_period: 15s
    volumes:
      - etc-pki:/etc/pki

  waf-init:
    command:
      - -c
      - |
        sed -i 's/1024/0/g' /variables.schema.json
        export ORO_GLOBAL_ROOT_CA_CERT=$(cat $$CAROOT/rootCA.pem)
        export ORO_GLOBAL_ROOT_CA_KEY=$(cat $$CAROOT/rootCA-key.pem)
        /docker-entrypoint.sh -m init
    environment:
      CAROOT: $ORO_CAROOT
    volumes:
      - ${CAROOT-/var/empty}:${CAROOT-/var/empty}
      - etc-pki:/etc/pki
      - ./config.rb:/config.rb

  behat:
    environment:
      CAROOT: $ORO_CAROOT
    volumes:
      - etc-pki:/etc/pki

  restore:
    environment:
      CAROOT:
      ORO_CAROOT:
    volumes:
      - cache:/var/www/oro/var/cache
      - ${CAROOT-/var/empty}:${CAROOT-/var/empty}
      - etc-pki:/etc/pki
      - ./../docker/docker-entrypoint-init.sh:/usr/local/bin/docker-entrypoint.sh

  chrome:
    environment:
      CAROOT: $ORO_CAROOT
    volumes:
      - etc-pki:/etc/pki

volumes:
  etc-pki: {}