version: "3.9"
x-depends_on: &default-depends_on
  "db":
    condition: service_healthy
  "mail":
    condition: service_started

services:
  application:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: -- true
    env_file:
      - .env
      - .env-orocommerce-application
    depends_on:
      "web":
        condition: service_started
      "consumer":
        condition: service_started
      "cron":
        condition: service_started

  web:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: nginx
    env_file:
      - .env
      - .env-orocommerce-application
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      "php-fpm-app":
        condition: service_healthy
      "ws":
        condition: service_started
    volumes:
      - cache:/var/www/oro/var/cache:ro
      - public_storage:/var/www/oro/public/media:ro
      - private_storage:/var/www/oro/var/data:ro
    networks:
      default:
        aliases:
          - ${ORO_APP_DOMAIN}
          - ${ORO_APP_ADDON_DOMAINS}

  web-behat:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: nginx
    env_file:
      - .env
      - .env-orocommerce-application
    restart: unless-stopped
    depends_on:
      "php-fpm-app":
        condition: service_healthy
      "ws":
        condition: service_started
    volumes:
      - cache:/var/www/oro/var/cache:ro
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data
    networks:
      default:
        aliases:
          - ${ORO_APP_DOMAIN}
          - ${ORO_APP_ADDON_DOMAINS}

  php-fpm-app:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: php-fpm
    env_file:
      - .env
      - .env-orocommerce-application
    healthcheck:
      test: "php-fpm-healthcheck"
      interval: 5s
      timeout: 30s
      start_period: 120s
    restart: unless-stopped
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  ws:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: job-runner run --no-ansi --attempts=30 --delay=5 --kill --present=/var/www/oro/bin/console --lock=/var/www/oro/var/cache/maintenance_lock --lock=/var/www/oro/maintenance_lock --lock=/var/www/oro/emergency_lock "php -ddisplay_errors=stderr /var/www/oro/bin/console gos:websocket:server -v"
    env_file:
      - .env
      - .env-orocommerce-application
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    init: true
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    volumes:
      - cache:/var/www/oro/var/cache:ro
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  consumer:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: job-runner run --no-ansi --attempts=30 --delay=5 --kill --present=/var/www/oro/bin/console --lock=/var/www/oro/var/cache/maintenance_lock --lock=/var/www/oro/maintenance_lock --lock=/var/www/oro/emergency_lock "php -ddisplay_errors=stderr /var/www/oro/bin/console oro:message-queue:consume --memory-limit=500 -v"
    env_file:
      - .env
      - .env-orocommerce-application
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    init: true
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    volumes:
      - cache:/var/www/oro/var/cache:ro
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  cron:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: cron
    env_file:
      - .env
      - .env-orocommerce-application
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 1048576
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    volumes:
      - cache:/var/www/oro/var/cache:ro
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  install:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: console oro:install --no-interaction --timeout=3600 --user-name="$ORO_USER_NAME" --user-email="$ORO_USER_EMAIL" --user-firstname="$ORO_USER_FIRSTNAME" --user-lastname="$ORO_USER_LASTNAME" --user-password="$ORO_USER_PASSWORD" --sample-data="$ORO_SAMPLE_DATA" --organization-name="$ORO_ORGANIZATION_NAME" --language=$ORO_LANGUAGE --formatting-code=$ORO_FORMATTING_CODE --application-url="$ORO_APP_PROTOCOL://$ORO_APP_DOMAIN" $ORO_INSTALL_OPTIONS
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
      - .env-orocommerce-application
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  install-test:
    image: $ORO_IMAGE_TEST:$ORO_IMAGE_TAG
    command: console oro:install --timeout=3600
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
      - .env-orocommerce-application
    environment:
      ORO_ENV: test
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  functional-init:
    image: $ORO_IMAGE_TEST:$ORO_IMAGE_TAG
    command: functional-init
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
      - .env-orocommerce-application
    environment:
      ORO_LOCAL_RUN:
      ORO_IMAGE_TAG:
      ORO_DB_STAT_HOST:
      TESTS_LIST:
      EXCLUDED_TESTS:
      ORO_TESTS_PATH:

  functional:
    image: $ORO_IMAGE_TEST:$ORO_IMAGE_TAG
    command: functional
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
      - .env-orocommerce-application
    environment:
      ORO_FUNCTIONAL_ARGS:
      ORO_LOCAL_RUN:
      ORO_IMAGE_TAG:
      ORO_DB_STAT_HOST:
      ORO_ENV: test
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  behat-init:
    image: $ORO_IMAGE_TEST:$ORO_IMAGE_TAG
    command: behat-init
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
      - .env-orocommerce-application
    environment:
      ORO_BEHAT_ARGS:
      ORO_LOCAL_RUN:
      ORO_IMAGE_TAG:
      ORO_DB_STAT_HOST:
      TESTS_LIST:
      ORO_BEHAT_TAGS:
      ORO_ARTIFACT_DIR:
      BUILD_URL:
    depends_on:
      <<: *default-depends_on

  behat:
    image: $ORO_IMAGE_TEST:$ORO_IMAGE_TAG
    command: behat
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
      - .env-orocommerce-application
    environment:
      ORO_BEHAT_ARGS:
      ORO_LOCAL_RUN:
      ORO_IMAGE_TAG:
      ORO_DB_STAT_HOST:
      ORO_BEHAT_TAGS:
      ORO_BEHAT_OPTIONS:
      ORO_ARTIFACT_DIR:
      BUILD_URL:
    depends_on:
      <<: *default-depends_on
      "consumer":
        condition: service_started
      "web-behat":
        condition: service_started
      "chrome":
        condition: service_healthy
    volumes:
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  behat-remote:
    image: $ORO_IMAGE_TEST:$ORO_IMAGE_TAG
    command: behat --skip-isolators
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
      - .env-orocommerce-application
    environment:
      ORO_BEHAT_ARGS:
      ORO_APP_PROTOCOL:
      ORO_APP_DOMAIN:
      ORO_APP_ADDON_DOMAINS:
      ORO_NGINX_HOST: ''
      ORO_BEHAT_OPTIONS:
      ORO_ARTIFACT_DIR:
      BUILD_URL:
    depends_on:
      "chrome":
        condition: service_healthy
      "mail":
        condition: service_started

  chrome:
    image: oroinc/chrome:$ORO_CHROME_VER
    command: chrome --allowed-ips 0.0.0.0/0 --allowed-origins=* --whitelisted-ips=""
    env_file:
      - .env
      - .env-orocommerce-application
    environment:
      ORO_APP_DOMAIN:
      ORO_APP_ADDON_DOMAINS:
      ORO_NGINX_HOST:
      ORO_SSL:
      ORO_APP_PROTOCOL:
      ORO_NGINX_HTTPS_PORT:
      ORO_NGINX_HTTP_PORT:
      ORO_CHROME_PORT:
      CAROOT:
      DBUS_SESSION_BUS_ADDRESS: /dev/null
    healthcheck:
      test: "curl -sf http://127.0.0.1:$${ORO_CHROME_PORT}/status"
      interval: 15s
      timeout: 30s
      start_period: 240s
    restart: unless-stopped
    volumes:
      - /dev/shm:/dev/shm

  backup:
    command: -- true
    env_file:
      - .env
      - .env-orocommerce-application
    build:
      context: ./../docker
      dockerfile: Dockerfile-init
      target: backup-files
      network: host
      args:
        ORO_IMAGE_FROM: $ORO_IMAGE
        ORO_IMAGE_TAG:
        ORO_DB_HOST:
        ORO_DB_PORT:
        ORO_DB_NAME:
        ORO_DB_USER:
        ORO_DB_PASSWORD:
        ORO_DB_ROOT_USER:
        ORO_DB_ROOT_PASSWORD:
      tags:
        - $ORO_IMAGE_INIT:$ORO_IMAGE_TAG
      extra_hosts:
        - db:${DB_IP-}
    depends_on:
      "db":
        condition: service_healthy

  backup-test:
    command: -- true
    env_file:
      - .env
      - .env-orocommerce-application
    build:
      context: ./../docker
      dockerfile: Dockerfile-init
      target: backup-files
      network: host
      args:
        ORO_IMAGE_FROM: $ORO_IMAGE
        ORO_IMAGE_TAG:
        ORO_DB_HOST:
        ORO_DB_PORT:
        ORO_DB_NAME:
        ORO_DB_USER:
        ORO_DB_PASSWORD:
        ORO_DB_ROOT_USER:
        ORO_DB_ROOT_PASSWORD:
      tags:
        - $ORO_IMAGE_INIT_TEST:$ORO_IMAGE_TAG
      extra_hosts:
        - db:${DB_IP-}
    depends_on:
      "db":
        condition: service_healthy

  restore:
    image: ${ORO_IMAGE_INIT}${ORO_LANGUAGE_SUFFIX-}:$ORO_IMAGE_TAG
    command: restore
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
      - .env-orocommerce-application
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  restore-test:
    image: $ORO_IMAGE_INIT_TEST:$ORO_IMAGE_TAG
    command: restore-test
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
      - .env-orocommerce-application
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  update:
    image: $ORO_IMAGE_INIT:$ORO_IMAGE_TAG
    command: update
    user: $ORO_USER_RUNTIME
    env_file: .env
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  update-test:
    image: $ORO_IMAGE_INIT_TEST:$ORO_IMAGE_TAG
    command: update
    user: $ORO_USER_RUNTIME
    env_file: .env
    environment:
      ORO_ENV: test
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  warmup-cache:
    image: $ORO_IMAGE_INIT:$ORO_IMAGE_TAG
    command: warmup-cache
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
      - .env-orocommerce-application
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  db:
    image: docker.io/oroinc/pgsql:${ORO_PG_VER}
    labels:
      com.symfony.server.service-prefix: ORO_DB
    environment:
      POSTGRES_ROOT_PASSWORD: ${ORO_DB_ROOT_PASSWORD}
      POSTGRES_DB: ${ORO_DB_NAME}
      POSTGRES_USER: ${ORO_DB_USER}
      POSTGRES_PASSWORD: ${ORO_DB_PASSWORD}
    healthcheck:
      test: "pg_isready -U$${POSTGRES_USER} -d$${POSTGRES_DB}"
      start_period: 60s
    restart: unless-stopped

  mail:
    image: schickling/mailcatcher
    hostname: mail
    restart: unless-stopped

volumes:
  cache: {}
  public_storage: {}
  private_storage: {}
