---
version: '3'

services:
  master:
    image: oroinc/jenkins:lts-almalinux
    env_file: .env
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jcasc
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - HOME_FOR_HOST=$PWD/agent
    healthcheck:
      test: curl -sSf --connect-timeout 1 -XGET -k http://localhost:8080/login > /dev/null
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jcasc:/var/jenkins_home/jcasc
    ports:
      - 8080:8080
      - 50000:50000

  docker-host:
    image: oroinc/agent:latest
    command: java -jar /usr/share/jenkins/agent.jar -jnlpUrl http://master:8080/manage/computer/docker%2Dhost/jenkins-agent.jnlp -workDir "$PWD/agent"
    user: $UID:$GID
    group_add:
      - $DOCKER_GROUP_ID
    working_dir: $PWD
    init: true
    security_opt:
    - label:disable
    depends_on:
      "master":
        condition: service_healthy
    tmpfs:
      - /tmp
    volumes:
      - $HOME:$HOME
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/shm:/dev/shm
      - /etc/group:/etc/group:ro
      - /etc/gshadow:/etc/gshadow:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro

volumes:
  jenkins_home:
