jobs:
  - script: >
      pipelineJob('docker-pipeline-example') {
        quietPeriod(0)
        definition {
          cps {
            script """
              pipeline {
                  agent { label 'docker1' }
                  stages {
                      stage('Build') {
                          agent {
                              docker {
                                  image 'oraclelinux:8-slim'
                                  reuseNode true
                              }
                          }
                          steps {
                              sh '''
                                cat /etc/os-release
                                printenv | sort
                                sleep 30
                              '''
                          }
                      }
                  }
              }
            """
            sandbox()
          }
        }
      }

      pipelineJob('orocommerce-application') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/oroinc/orocommerce-application')
                }
                branch('5.1')
              }
            }
            lightweight()
          }
        }
      }
